if(!window.TypekitPreview)window.TypekitPreview={};window.TypekitPreview.config={"pi":"//use.typekit.net/c/{id}/{description}/{format}{/extras*}?{token}","pk":"//use.typekit.net/p/{id}/{description}/{format}{/extras*}?{token}"};
;(function(window,document,undefined){
function aa(a,b,d){return a.call.apply(a.bind,arguments)}function ba(a,b,d){if(!a)throw Error();if(2<arguments.length){var c=Array.prototype.slice.call(arguments,2);return function(){var d=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(d,c);return a.apply(b,d)}}return function(){return a.apply(b,arguments)}}function h(a,b,d){h=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?aa:ba;return h.apply(null,arguments)}var ca=Date.now||function(){return+new Date};
function ea(a,b){this.da=a;this.N=b||a;this.K=this.N.document}ea.prototype.createElement=function(a,b,d){a=this.K.createElement(a);if(b)for(var c in b)b.hasOwnProperty(c)&&("style"==c?a.style.cssText=b[c]:a.setAttribute(c,b[c]));d&&a.appendChild(this.K.createTextNode(d));return a};function fa(a,b,d){a=a.K.getElementsByTagName(b)[0];a||(a=document.documentElement);a&&a.lastChild&&a.insertBefore(d,a.lastChild)}function ga(a,b){function d(){a.K.body?b():setTimeout(d,0)}d()}
function n(a,b,d){b=b||[];d=d||[];for(var c=a.className.split(/\s+/),e=0;e<b.length;e+=1){for(var f=!1,g=0;g<c.length;g+=1)if(b[e]===c[g]){f=!0;break}f||c.push(b[e])}b=[];for(e=0;e<c.length;e+=1){f=!1;for(g=0;g<d.length;g+=1)if(c[e]===d[g]){f=!0;break}f||b.push(c[e])}a.className=b.join(" ").replace(/\s+/g," ").replace(/^\s+|\s+$/,"")}function ha(a,b){for(var d=a.className.split(/\s+/),c=0,e=d.length;c<e;c++)if(d[c]==b)return!0;return!1}
function ia(a,b){var d=a.createElement("link",{rel:"stylesheet",href:b,media:"all"}),c=!1;d.onload=function(){c||(c=!0)};d.onerror=function(){c||(c=!0)};fa(a,"head",d)}function ja(a){this.qa=a||"-"}ja.prototype.f=function(a){for(var b=[],d=0;d<arguments.length;d++)b.push(arguments[d].replace(/[\W_]+/g,"").toLowerCase());return b.join(this.qa)};function ka(a,b){this.e=a;this.q=a.N.document.documentElement;this.Q=b;this.m="wf";this.l=new ja("-");this.ja=!1!==b.events;this.C=!1!==b.classes}
function la(a){a.C&&n(a.q,[a.l.f(a.m,"loading")]);p(a,"loading")}function r(a){if(a.C){var b=ha(a.q,a.l.f(a.m,"active")),d=[],c=[a.l.f(a.m,"loading")];b||d.push(a.l.f(a.m,"inactive"));n(a.q,d,c)}p(a,"inactive")}function p(a,b,d){if(a.ja&&a.Q[b])if(d)a.Q[b](d.getName(),s(d));else a.Q[b]()}function v(a,b){this.O=a;this.W=4;this.P="n";var d=(b||"n4").match(/^([nio])([1-9])$/i);d&&(this.P=d[1],this.W=parseInt(d[2],10))}v.prototype.getName=function(){return this.O};function s(a){return a.P+a.W}
function x(a,b){this.e=a;this.G=b;this.n=this.e.createElement("span",{"aria-hidden":"true"},this.G)}function y(a){fa(a.e,"body",a.n)}
function z(a){var b;b=[];for(var d=a.O.split(/,\s*/),c=0;c<d.length;c++){var e=d[c].replace(/['"]/g,"");-1==e.indexOf(" ")?b.push(e):b.push("'"+e+"'")}b=b.join(",");d="normal";"o"===a.P?d="oblique":"i"===a.P&&(d="italic");return"display:block;position:absolute;top:-9999px;left:-9999px;font-size:300px;width:auto;height:auto;line-height:normal;margin:0;padding:0;font-variant:normal;white-space:nowrap;font-family:"+b+";"+("font-style:"+d+";font-weight:"+(a.W+"00")+";")}
x.prototype.remove=function(){var a=this.n;a.parentNode&&a.parentNode.removeChild(a)};
function ma(a,b,d,c,e,f,g){this.X=a;this.oa=b;this.e=d;this.p=c;this.G=g||"BESbswy";this.A={};this.V=e||3E3;this.ea=f||null;this.F=this.w=this.v=null;this.v=new x(this.e,this.G);this.w=new x(this.e,this.G);this.F=new x(this.e,this.G);a=new v("serif",s(this.p));a=z(a);this.v.n.style.cssText=a;a=new v("sans-serif",s(this.p));a=z(a);this.w.n.style.cssText=a;a=new v("monospace",s(this.p));a=z(a);this.F.n.style.cssText=a;y(this.v);y(this.w);y(this.F)}
var A={Ea:"serif",Da:"sans-serif",Aa:"monospace"},B=null;function na(){if(null===B){var a=/AppleWebKit\/([0-9]+)(?:\.([0-9]+))/.exec(window.navigator.userAgent);B=!!a&&(536>parseInt(a[1],10)||536===parseInt(a[1],10)&&11>=parseInt(a[2],10))}return B}
ma.prototype.start=function(){this.A.serif=this.v.n.offsetWidth;this.A["sans-serif"]=this.w.n.offsetWidth;this.A.monospace=this.F.n.offsetWidth;this.ua=ca();var a=new v(this.p.getName()+",serif",s(this.p)),a=z(a);this.v.n.style.cssText=a;a=new v(this.p.getName()+",sans-serif",s(this.p));a=z(a);this.w.n.style.cssText=a;oa(this)};function pa(a,b,d){for(var c in A)if(A.hasOwnProperty(c)&&b===a.A[A[c]]&&d===a.A[A[c]])return!0;return!1}
function oa(a){var b=a.v.n.offsetWidth,d=a.w.n.offsetWidth,c;(c=b===a.A.serif&&d===a.A["sans-serif"])||(c=na()&&pa(a,b,d));c?ca()-a.ua>=a.V?na()&&pa(a,b,d)&&(null===a.ea||a.ea.hasOwnProperty(a.p.getName()))?C(a,a.X):C(a,a.oa):qa(a):C(a,a.X)}function qa(a){setTimeout(h(function(){oa(this)},a),50)}function C(a,b){a.v.remove();a.w.remove();a.F.remove();b(a.p)}function D(a,b,d){this.e=a;this.B=b;this.R=0;this.ha=this.ca=!1;this.V=d}
D.prototype.ka=function(a){var b=this.B;b.C&&n(b.q,[b.l.f(b.m,a.getName(),s(a).toString(),"active")],[b.l.f(b.m,a.getName(),s(a).toString(),"loading"),b.l.f(b.m,a.getName(),s(a).toString(),"inactive")]);p(b,"fontactive",a);this.ha=!0;ra(this)};
D.prototype.ma=function(a){var b=this.B;if(b.C){var d=ha(b.q,b.l.f(b.m,a.getName(),s(a).toString(),"active")),c=[],e=[b.l.f(b.m,a.getName(),s(a).toString(),"loading")];d||c.push(b.l.f(b.m,a.getName(),s(a).toString(),"inactive"));n(b.q,c,e)}p(b,"fontinactive",a);ra(this)};function ra(a){0==--a.R&&a.ca&&(a.ha?(a=a.B,a.C&&n(a.q,[a.l.f(a.m,"active")],[a.l.f(a.m,"loading"),a.l.f(a.m,"inactive")]),p(a,"active")):r(a.B))}
function E(a,b,d,c){this.g=null!=a?a:null;this.r=null!=b?b:null;this.H=null!=d?d:null;this.f=null!=c?c:null}var sa=/^([0-9]+)(?:[\._-]([0-9]+))?(?:[\._-]([0-9]+))?(?:[\._+-]?(.*))?$/;E.prototype.compare=function(a){return this.g>a.g||this.g===a.g&&this.r>a.r||this.g===a.g&&this.r===a.r&&this.H>a.H?1:this.g<a.g||this.g===a.g&&this.r<a.r||this.g===a.g&&this.r===a.r&&this.H<a.H?-1:0};function F(a,b){return-1===a.compare(b)}function G(a,b){return 0===a.compare(b)||1===a.compare(b)}
function H(a,b){return 0===a.compare(b)}E.prototype.toString=function(){return[this.g,this.r||"",this.H||"",this.f||""].join("")};function J(a){a=sa.exec(a);var b=null,d=null,c=null,e=null;a&&(null!==a[1]&&a[1]&&(b=parseInt(a[1],10)),null!==a[2]&&a[2]&&(d=parseInt(a[2],10)),null!==a[3]&&a[3]&&(c=parseInt(a[3],10)),null!==a[4]&&a[4]&&(e=/^[0-9]+$/.test(a[4])?parseInt(a[4],10):a[4]));return new E(b,d,c,e)}function K(a,b,d,c,e,f,g){this.O=a;this.t=b;this.D=d;this.L=c;this.h=e;this.c=f;this.S=g}
K.prototype.getName=function(){return this.O};function ta(a,b){this.b=a;this.J=b}var ua=new K("Unknown",new E,"Unknown",new E,"Unknown",new E,void 0);
ta.prototype.parse=function(){var a;if(-1!=this.b.indexOf("MSIE")||-1!=this.b.indexOf("Trident/")){a=L(this);var b=J(M(this)),d=null,c=null,e=null,e=N(this.b,/Trident\/([\d\w\.]+)/,1),f=O(this.J),d=-1!=this.b.indexOf("MSIE")?J(N(this.b,/MSIE ([\d\w\.]+)/,1)):J(N(this.b,/rv:([\d\w\.]+)/,1));""!=e?(c="Trident",e=J(e)):(c="Unknown",e=new E);a=new K("MSIE",d,c,e,a,b,f)}else if(-1!=this.b.indexOf("Opera"))a:if(a="Unknown",b=J(N(this.b,/Presto\/([\d\w\.]+)/,1)),d=J(M(this)),c=O(this.J),null!==b.g?a="Presto":
(-1!=this.b.indexOf("Gecko")&&(a="Gecko"),b=J(N(this.b,/rv:([^\)]+)/,1))),-1!=this.b.indexOf("Opera Mini/"))f=J(N(this.b,/Opera Mini\/([\d\.]+)/,1)),a=new K("OperaMini",f,a,b,L(this),d,c);else{if(-1!=this.b.indexOf("Version/")&&(f=J(N(this.b,/Version\/([\d\.]+)/,1)),null!==f.g)){a=new K("Opera",f,a,b,L(this),d,c);break a}f=J(N(this.b,/Opera[\/ ]([\d\.]+)/,1));a=null!==f.g?new K("Opera",f,a,b,L(this),d,c):new K("Opera",new E,a,b,L(this),d,c)}else/OPR\/[\d.]+/.test(this.b)?a=va(this):/AppleWeb(K|k)it/.test(this.b)?
a=va(this):-1!=this.b.indexOf("Gecko")?(a="Unknown",b=new E,d=J(M(this)),-1!=this.b.indexOf("Firefox")?(a="Firefox",b=J(N(this.b,/Firefox\/([\d\w\.]+)/,1))):-1!=this.b.indexOf("Mozilla")&&(a="Mozilla"),c=J(N(this.b,/rv:([^\)]+)/,1)),a=new K(a,b,"Gecko",c,L(this),d,O(this.J))):a=ua;return a};
function L(a){var b=N(a.b,/(iPod|iPad|iPhone|Android|Windows Phone|BB\d{2}|BlackBerry)/,1);if(""!=b)return/BB\d{2}/.test(b)&&(b="BlackBerry"),b;a=N(a.b,/(Linux|Mac_PowerPC|Macintosh|Windows|CrOS|PlayStation|CrKey)/,1);return""!=a?("Mac_PowerPC"==a?a="Macintosh":"PlayStation"==a&&(a="Linux"),a):"Unknown"}
function M(a){var b=N(a.b,/(OS X|Windows NT|Android) ([^;)]+)/,2);if(b||(b=N(a.b,/Windows Phone( OS)? ([^;)]+)/,2))||(b=N(a.b,/(iPhone )?OS ([\d_]+)/,2)))return b;if(b=N(a.b,/(?:Linux|CrOS|CrKey) ([^;)]+)/,1))for(var b=b.split(/\s/),d=0;d<b.length;d+=1)if(/^[\d\._]+$/.test(b[d]))return b[d];return(a=N(a.b,/(BB\d{2}|BlackBerry).*?Version\/([^\s]*)/,2))?a:"Unknown"}
function va(a){var b=L(a),d=J(M(a)),c=J(N(a.b,/AppleWeb(?:K|k)it\/([\d\.\+]+)/,1)),e="Unknown",f=new E,f="Unknown";/OPR\/[\d.]+/.test(a.b)?e="Opera":-1!=a.b.indexOf("Chrome")||-1!=a.b.indexOf("CrMo")||-1!=a.b.indexOf("CriOS")?e="Chrome":/Silk\/\d/.test(a.b)?e="Silk":"BlackBerry"==b||"Android"==b?e="BuiltinBrowser":-1!=a.b.indexOf("PhantomJS")?e="PhantomJS":-1!=a.b.indexOf("Safari")?e="Safari":-1!=a.b.indexOf("AdobeAIR")?e="AdobeAIR":-1!=a.b.indexOf("PlayStation")&&(e="BuiltinBrowser");"BuiltinBrowser"==
e?f="Unknown":"Silk"==e?f=N(a.b,/Silk\/([\d\._]+)/,1):"Chrome"==e?f=N(a.b,/(Chrome|CrMo|CriOS)\/([\d\.]+)/,2):-1!=a.b.indexOf("Version/")?f=N(a.b,/Version\/([\d\.\w]+)/,1):"AdobeAIR"==e?f=N(a.b,/AdobeAIR\/([\d\.]+)/,1):"Opera"==e?f=N(a.b,/OPR\/([\d.]+)/,1):"PhantomJS"==e&&(f=N(a.b,/PhantomJS\/([\d.]+)/,1));f=J(f);return new K(e,f,"AppleWebKit",c,b,d,O(a.J))}function N(a,b,d){return(a=a.match(b))&&a[d]?a[d]:""}function O(a){if(a.documentMode)return a.documentMode}function P(a){this.e=a}
P.prototype.toString=function(){var a=this.e;return encodeURIComponent(a.N.location.hostname||a.da.location.hostname)};function wa(a,b){this.o=a;this.aa=b}wa.prototype.toString=function(){for(var a=[],b=0;b<this.aa.length;b++)for(var d=this.aa[b],c=d.s(),d=d.s(this.o),e=0;e<c.length;e++){var f;a:{for(f=0;f<d.length;f++)if(c[e]===d[f]){f=!0;break a}f=!1}a.push(f?1:0)}a=a.join("");a=a.replace(/^0+/,"");b=[];for(c=a.length;0<c;c-=4)b.unshift(parseInt(a.slice(0>c-4?0:c-4,c),2).toString(16));return b.join("")};
function xa(a){this.wa=a}xa.prototype.f=function(a,b){var d=b||{},c=this.wa.replace(/\{\/?([^*}]*)(\*?)\}/g,function(a,b,c){return c&&d[b]?"/"+d[b].join("/"):d[b]||""});c.match(/^\/\//)&&(c=(a?"https:":"http:")+c);return c.replace(/\/*\?*($|\?)/,"$1")};function ya(a,b,d,c,e){this.u=a;this.M=b;this.na=d;this.va=c;this.sa=e;this.ba={};this.T={}}ya.prototype.s=function(a){return a?(this.ba[a]||this.M).slice(0):this.M.slice(0)};
function za(a,b){for(var d=a.s(b),c=a.T[b]||[],e=[],f=0;f<d.length;f++)e.push(new v(a.u,d[f]));for(f=0;f<c.length;f++)if(d=c[f].u,d!==a.u)for(var g=c[f].s(),k=0;k<g.length;k++)e.push(new v(d,g[k]));return e}function Aa(a,b){this.u=a;this.M=b}Aa.prototype.s=function(){return this.M};function Ba(){this.ia=this.xa=this.I=this.U=this.pa=!0}function Q(a){return"Windows"===a.h}function R(a){return Q(a)&&H(a.c,new E(5,1))||Q(a)&&H(a.c,new E(5,2))||Q(a)&&H(a.c,new E(6,0))||Q(a)&&G(a.c,new E(6,1))}
function T(a){return"Macintosh"===a.h&&(G(a.c,new E(10,4))||null===a.c.g)}function U(a,b){return b.pa&&("iPhone"===a.h||"iPod"===a.h)}function Ca(a,b){return U(a,b)&&G(a.c,new E(4,2))&&F(a.c,new E(5))}function Da(a,b){return b.U&&"iPad"===a.h&&G(a.c,new E(4,2))&&F(a.c,new E(5))}function V(a,b){return b.I&&"Android"===a.h}function Ea(a,b){return V(a,b)&&G(a.c,new E(2,2))&&F(a.c,new E(3,1))}function Fa(a,b){return V(a,b)&&G(a.c,new E(3,1))&&F(a.c,new E(4,1))}
function W(a){return"Linux"===a.h||"Ubuntu"===a.h}function Ga(a){return"Safari"===a.getName()&&"AppleWebKit"===a.D||"Unknown"===a.getName()&&"AppleWebKit"===a.D&&("iPhone"===a.h||"iPad"===a.h||"iPod"===a.h)}function X(a){return"BuiltinBrowser"===a.getName()}function Ha(a){this.ga=a}function Ia(a,b){return b}
var Y={Ba:"a",Fa:"d",za:"i",Ca:"j",ya:"k",NONE:"x"},Z={a:function(a,b){return"Safari"===a.getName()&&"AppleWebKit"===a.D&&G(a.L,new E(525,13))&&F(a.L,new E(534,50))&&(R(a)||T(a))||X(a)&&(Ea(a,b)||V(a,b)&&G(a.c,new E(4,1)))||b.I&&"Silk"===a.getName()&&F(a.t,new E(2))&&(Ea(a,b)||T)||b.I&&"Silk"===a.getName()&&G(a.t,new E(2))&&V(a,b)&&G(a.c,new E(4,1))||Ga(a)&&(Da(a,b)||Ca(a,b))||"Chrome"===a.getName()&&G(a.t,new E(6))&&(Da(a,b)||Ca(a,b))||"AdobeAIR"===a.getName()&&G(a.t,new E(2,5))&&(Q(a)&&null===a.c.g||
W(a)||T(a))},d:function(a,b){return"Chrome"===a.getName()&&G(a.t,new E(6))&&(R(a)||W(a)||T(a)||V(a,b)||"CrOS"===a.h||"CrKey"===a.h||b.U&&"iPad"===a.h&&G(a.c,new E(5))||U(a,b)&&G(a.c,new E(5)))||"Gecko"===a.D&&1===a.L.compare(new E(1,9,1))&&(R(a)||W(a)||T(a)||V(a,b))||"Safari"===a.getName()&&"AppleWebKit"===a.D&&G(a.L,new E(534,50))&&(R(a)||T(a))||Ga(a)&&(b.U&&"iPad"===a.h&&G(a.c,new E(5))||U(a,b)&&G(a.c,new E(5)))||"Opera"===a.getName()&&G(a.t,new E(11,10))&&(R(a)||W(a)||T(a)||V(a,b))||"MSIE"===a.getName()&&
9<=a.S&&(Q(a)&&G(a.c,new E(6,1))||Q(a)&&H(a.c,new E(6,0)))||"MSIE"===a.getName()&&b.xa&&"Windows Phone"===a.h&&G(a.c,new E(8))||X(a)&&(b.ia&&"BlackBerry"===a.h&&G(a.c,new E(10))||W(a))},j:function(a,b){return X(a)&&Fa(a,b)||b.I&&"Silk"===a.getName()&&G(a.t,new E(2))&&(Fa(a,b)||W(a))},i:function(a){return"MSIE"===a.getName()&&G(a.t,new E(6,0))&&(void 0===a.S||9>a.S)&&R(a)},x:function(){return!1}};
function Ja(){var a=Ka,b=new Ba,d=new Ba||b,c;for(c in Y){var e=Y[c];if(Z[e]&&Z[e](a,d))return e}for(c in Y)if(e=Y[c],Z[e]&&Z[e](a,b))return"x";return"k"}var La={};
La.i=new Ha(function(a,b,d){for(var c=0;c<b.length;c+=1){var e=b[c],f;f=e;f=a.replace(/(-1|-2)$/,"").slice(0,28)+"-"+f;d.push(new Aa(f,[e]))}a={};for(e=0;e<b.length;e++)d=b[e],c=d.charAt(1),(a[c]||(a[c]=[])).push(d);d=[[4,3,2,1,5,6,7,8,9],[7,8,9,6,5,4,3,2,1]];c=[];for(e=0;e<d.length;e++){f=d[e];for(var g=0;g<f.length;g++){var k=f[g];if(a[k]){c=c.concat(a[k]);break}}}d=c;c={};a=[];for(e=0;e<d.length;e++)f=d[e],c[f]||(c[f]=!0,a.push(f));d=[];for(c=0;c<b.length;c++)for(e=b[c],f=0;f<a.length;f++)g=a[f],
g==e&&d.push(g);return d});var $={};$.a=$.d=$.j=function(){return[]};$.i=function(a,b,d){return[new P(a),new wa(b,d)]};$.k=function(a){return[new P(a)]};var Ma={all:1,"default":2};function Na(a,b,d,c,e,f,g){this.ra=a;this.o=d;this.la=c;this.e=e;this.b=f;this.q=g;this.Y="anonymous";this.Z=null;this.$="default"}Na.prototype.ta=function(a){var b=a.auth_id;b&&(this.Y=b);if(b=a.auth_token)this.Z=b;(b=a.default_subset)&&Ma[b]&&(this.$=b);a.protocol&&(a=a.protocol,/^http(s)?:$/.test(a)&&(this.e.fa=a))};
Na.prototype.load=function(a,b){for(var d=b||{},c=a=Oa(this,a),e=[],f=0;f<c.length;f++){var g=c[f];e.push(new ya(g.css_name,g.variations,g.id,g.subset,g.primer))}c=null;if("x"!==this.o){for(c=0;c<e.length;c++){for(var f=e[c],g=this.o,k=this.la,l=[],m=f.u.split(",")[0].replace(/"|'/g,""),q=l,w=f.s(),u=void 0,I=[],S={},t=0;t<w.length;t++)u=w[t],0<u.length&&!S[u]&&(S[u]=!0,I.push(u));w=I;m=k.ga?k.ga(m,w,q):w;f.ba[g]=m;f.T[g]=l}c=a;f=[];c.length&&f.push("1w");for(g=0;g<c.length;g++){l=c[g];m=[];m.push(l.css_name);
m.push(l.id);(q=l.primer)&&64===q.length?m.push(l.primer):m.push(Ma[l.subset]);for(q=0;q<l.variations.length;q++)m.push(l.variations[q]);f.push(m.join(","))}c=f.join(";");f=this.o;l=$[f](this.e,f,e);f=this.Y;g=this.Z||void 0;m=this.o;q=[];for(k=0;k<l.length;k++)q.push(l[k].toString());l={format:m,extras:q};l.id=f;l.description=c;g&&(l.token=g);c=this.e;"string"===typeof c.fa?c=c.fa:(f=c.N.location.protocol,"about:"==f&&(f=c.da.location.protocol),c="https:"==f?"https:":"http:");c=this.ra.f("https:"===
c,l)}if(Pa(this,e,c,d)){d=[];for(c=0;c<e.length;c++)for(m=e[c],q=m.s(this.o),f=m.na,g=m.va,l=m.sa,0<q.length&&d.push(Qa(f,q,m.u,g,l)),m=m.T[this.o]||[],q=0;q<m.length;q++)k=m[q],d.push(Qa(f,k.s(),k.u,g,l));e=d}else e=[];return e};
function Pa(a,b,d,c){var e=new ka(a.e,c);if("x"===a.o)return r(e),!1;if(b.length){var f=[],g={},k=new D(a.e,e,c.timeout);for(c=0;c<b.length;c++)f=f.concat(za(b[c],a.o));for(c=0;c<f.length;c++)g[f[c].getName()]="BESbswy\ue000\ue001\ue002\ue003\ue004\ue005\ue006";la(e);ia(a.e,d);ga(a.e,function(){var a=f,b={},c=g||{};if(0===a.length)r(k.B);else{k.R+=a.length;k.ca=!0;var d,e=[];for(d=0;d<a.length;d++){var I=a[d],S=c[I.getName()],t=k.B,da=I;t.C&&n(t.q,[t.l.f(t.m,da.getName(),s(da).toString(),"loading")]);
p(t,"fontloading",da);t=null;t=new ma(h(k.ka,k),h(k.ma,k),k.e,I,k.V,b,S);e.push(t)}for(d=0;d<e.length;d++)e[d].start()}})}return!0}
function Oa(a,b){for(var d=[],c=0;c<b.length;c++){var e=/^[A-Za-z0-9_-]+$/,f=b[c],g=f.id,k=f.variations,l=f.css_name,l=l&&"string"==typeof l&&l.match(e)?l:g,m=f.subset,m=Ma[m]?m:a.$,f=(f=f.primer)&&64===f.length?f:null;if("string"==typeof g&&g.match(e)&&"object"==typeof k&&0<k.length){for(var e={},q=[],w=0;w<k.length;w++){var u=k[w];u&&0<u.length&&!e[u]&&(q.push(u),e[u]=!0)}0<q.length&&d.push(Qa(g,q.sort(),l,m,f))}}return d.sort(function(a,b){var c=a.css_name,d=b.css_name;return c<d?-1:c>d?1:0})}
function Qa(a,b,d,c,e){return{id:a,variations:b,css_name:d,subset:c,primer:e}}window.TypekitPreview||(window.TypekitPreview={});if(!window.TypekitPreview.load){var Ra=new xa((window.TypekitPreview.config||{}).pk),Ka=(new ta(navigator.userAgent,document)).parse(),Sa=Ja(),Ta=new Na(Ra,0,Sa,La[Sa]||new Ha(Ia),new ea(window),Ka,document.documentElement);window.TypekitPreview=Ta;window.TypekitPreview.setup=Ta.ta;window.TypekitPreview.load=Ta.load};
})(this,document);
